# MeTube - Self-hosted YouTube downloader with web UI
# This setup allows you to modify the code and see changes reflected in the running container

services:
  metube:
    build: .
    container_name: MeTube
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      # Tells MeTube to use separate directories for video and audio downloads
      - DOWNLOAD_DIR=/downloads/video
      - AUDIO_DOWNLOAD_DIR=/downloads/audio
      # Sensible filename templates for downloads
      - OUTPUT_TEMPLATE=%(artist,uploader)s/%(artist,uploader)s - %(title)s%(genre& [%s]|)s (%(release_date>%Y-%m-%d,upload_date>%Y-%m-%d)s).%(ext)s
      - OUTPUT_TEMPLATE_PLAYLIST=%(playlist_title)s/%(artist,uploader)s - %(title)s%(genre& [%s]|)s (%(release_date>%Y-%m-%d,upload_date>%Y-%m-%d)s).%(ext)s
      # Development environment
      - PYTHONUNBUFFERED=1
    volumes:
      # Maps your local paths to the container paths
      - ${VIDEO_DOWNLOAD_DIR:-./downloads/video}:/downloads/video
      - ${AUDIO_DOWNLOAD_DIR:-./downloads/audio}:/downloads/audio
      # Mount source code for live editing
      - ./app:/app/app
    # Override the entrypoint to run Python directly for easier development
    command: ["python", "-u", "app/main.py"]
